import { User, Conversation, Message, CallSession, DisappearingTimerValue, UserPreferences } from '../types';
import { ISignalService } from './ISignalService';

export const CURRENT_USER: User = {
  id: 'user_me',
  phoneNumber: '+1 (555) 019-2834',
  username: 'pratham.01',
  displayName: 'Pratham',
  avatarUrl: '/images/avatars/avatar_fox.svg',
  about: 'Signal is my safe space 🔒',
  safetyNumber: '42918 09281 74819 02938 18492 84920 18492 84920 18492 84920 18492 84920',
  isVerified: true,
  color: '#2c6bed',
};

export const INITIAL_CONTACTS: User[] = [
  {
    id: 'user_sarah',
    phoneNumber: '+1 (555) 234-5678',
    username: 'sarah_connor',
    displayName: 'Sarah Connor',
    avatarUrl: '/images/avatars/avatar_cat.svg',
    about: 'No fate but what we make.',
    safetyNumber: '11928 34918 02938 18492 84920 18492 84920 18492 84920 18492 84920 39481',
    isVerified: true,
    color: '#9c27b0',
    lastSeen: Date.now() - 1000 * 60 * 5,
  },
  {
    id: 'user_alex',
    phoneNumber: '+1 (555) 876-5432',
    username: 'alex_m',
    displayName: 'Alex Miller',
    avatarUrl: '/images/avatars/avatar_dog.svg',
    about: 'Coffee & Code ☕💻',
    safetyNumber: '99281 74819 02938 18492 84920 18492 84920 18492 84920 18492 84920 28194',
    isVerified: true,
    color: '#00897b',
    lastSeen: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: 'user_elena',
    phoneNumber: '+1 (555) 432-1098',
    username: 'elena_rostova',
    displayName: 'Elena Rostova',
    avatarUrl: '/images/avatars/avatar_ghost.svg',
    about: 'In transit ✈️',
    safetyNumber: '55192 83948 10293 84756 19283 74650 19283 74650 19283 74650 19283 04928',
    isVerified: false,
    color: '#e91e63',
    lastSeen: Date.now() - 1000 * 60 * 30,
  },
  {
    id: 'user_david',
    phoneNumber: '+1 (555) 345-6789',
    username: 'david_k',
    displayName: 'David Kim',
    avatarUrl: '/images/avatars/avatar_sloth.svg',
    about: 'Offline for the weekend 🏕️',
    safetyNumber: '77291 03948 19283 74650 19283 74650 19283 74650 19283 74650 19283 91827',
    isVerified: true,
    color: '#ff9800',
    lastSeen: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: 'user_note_to_self',
    phoneNumber: '+1 (555) 019-2834',
    username: 'note_to_self',
    displayName: 'Note to Self',
    avatarUrl: '/images/icons/v3/note/note.svg',
    about: 'Personal clipboard, reminders & saved files',
    safetyNumber: '00000 00000 00000 00000 00000 00000 00000 00000 00000 00000 00000 00000',
    isVerified: true,
    color: '#5e5e5e',
  }
];

const now = Date.now();

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_note_to_self',
    type: 'direct',
    name: 'Note to Self',
    avatarUrl: '',
    color: '#5e5e5e',
    participants: [CURRENT_USER],
    isPinned: true,
    isMuted: false,
    isArchived: false,
    unreadCount: 0,
    disappearingTimer: 0,
    createdAt: now - 1000 * 60 * 60 * 24 * 30,
    updatedAt: now - 1000 * 60 * 12,
    lastMessage: {
      id: 'msg_nts_1',
      conversationId: 'conv_note_to_self',
      senderId: 'user_me',
      timestamp: now - 1000 * 60 * 12,
      content: 'Remember to verify the Safety Number before transmitting keys 🔑',
      type: 'text',
      status: 'read',
      reactions: [{ emoji: '📌', count: 1, userIds: ['user_me'] }],
      isNoteToSelf: true,
    }
  },
  {
    id: 'conv_sarah',
    type: 'direct',
    name: 'Sarah Connor',
    avatarUrl: '/images/avatars/avatar_cat.svg',
    color: '#9c27b0',
    participants: [CURRENT_USER, INITIAL_CONTACTS[0]],
    isPinned: true,
    isMuted: false,
    isArchived: false,
    unreadCount: 2,
    disappearingTimer: 86400, // 1 day
    createdAt: now - 1000 * 60 * 60 * 24 * 10,
    updatedAt: now - 1000 * 60 * 2,
    lastMessage: {
      id: 'msg_sarah_4',
      conversationId: 'conv_sarah',
      senderId: 'user_sarah',
      timestamp: now - 1000 * 60 * 2,
      content: 'Just deployed the new E2E verification test. Can you check on your side?',
      type: 'text',
      status: 'delivered',
      reactions: [{ emoji: '👍', count: 1, userIds: ['user_me'] }],
      isDisappearing: true,
      expireTimerSeconds: 86400,
      expiresAt: now + 86400 * 1000,
    }
  },
  {
    id: 'conv_alex',
    type: 'direct',
    name: 'Alex Miller',
    avatarUrl: '/images/avatars/avatar_dog.svg',
    color: '#00897b',
    participants: [CURRENT_USER, INITIAL_CONTACTS[1]],
    isPinned: false,
    isMuted: false,
    isArchived: false,
    unreadCount: 0,
    disappearingTimer: 0,
    createdAt: now - 1000 * 60 * 60 * 24 * 5,
    updatedAt: now - 1000 * 60 * 45,
    lastMessage: {
      id: 'msg_alex_2',
      conversationId: 'conv_alex',
      senderId: 'user_me',
      timestamp: now - 1000 * 60 * 45,
      content: 'Here is the voice memo detailing the architecture:',
      type: 'audio',
      status: 'read',
      reactions: [{ emoji: '❤️', count: 1, userIds: ['user_alex'] }],
      attachments: [{
        id: 'att_voice_1',
        url: '/sounds/notification.ogg',
        fileName: 'Voice message.ogg',
        fileSize: 32667,
        mimeType: 'audio/ogg',
        duration: 14,
        waveform: [0.2, 0.4, 0.8, 0.6, 0.9, 0.3, 0.5, 0.7, 1.0, 0.4, 0.2, 0.6, 0.8, 0.5, 0.3, 0.7, 0.9, 0.4, 0.2],
      }],
    }
  },
  {
    id: 'conv_core_team',
    type: 'group',
    name: 'Signal Web Core Team 🚀',
    avatarUrl: '/images/avatars/avatar_celebration.svg',
    color: '#2c6bed',
    participants: [CURRENT_USER, INITIAL_CONTACTS[0], INITIAL_CONTACTS[1], INITIAL_CONTACTS[2]],
    isPinned: false,
    isMuted: false,
    isArchived: false,
    unreadCount: 0,
    disappearingTimer: 3600, // 1 hour
    createdAt: now - 1000 * 60 * 60 * 24 * 14,
    updatedAt: now - 1000 * 60 * 60 * 3,
    lastMessage: {
      id: 'msg_team_3',
      conversationId: 'conv_core_team',
      senderId: 'user_elena',
      timestamp: now - 1000 * 60 * 60 * 3,
      content: 'Meeting moved to 4 PM UTC. Don’t forget to test the video calling pipeline!',
      type: 'text',
      status: 'read',
      reactions: [
        { emoji: '🚀', count: 3, userIds: ['user_me', 'user_sarah', 'user_alex'] },
        { emoji: '🔥', count: 2, userIds: ['user_me', 'user_alex'] },
      ],
    }
  },
  {
    id: 'conv_david',
    type: 'direct',
    name: 'David Kim',
    avatarUrl: '/images/avatars/avatar_sloth.svg',
    color: '#ff9800',
    participants: [CURRENT_USER, INITIAL_CONTACTS[3]],
    isPinned: false,
    isMuted: true,
    isArchived: false,
    unreadCount: 0,
    disappearingTimer: 0,
    createdAt: now - 1000 * 60 * 60 * 24 * 20,
    updatedAt: now - 1000 * 60 * 60 * 24 * 2,
    lastMessage: {
      id: 'msg_david_1',
      conversationId: 'conv_david',
      senderId: 'user_david',
      timestamp: now - 1000 * 60 * 60 * 24 * 2,
      content: 'See you next Monday. Have a nice weekend!',
      type: 'text',
      status: 'read',
      reactions: [],
    }
  },
  {
    id: 'conv_archived_1',
    type: 'direct',
    name: 'Elena Rostova',
    avatarUrl: '/images/avatars/avatar_ghost.svg',
    color: '#e91e63',
    participants: [CURRENT_USER, INITIAL_CONTACTS[2]],
    isPinned: false,
    isMuted: false,
    isArchived: true,
    unreadCount: 0,
    disappearingTimer: 0,
    createdAt: now - 1000 * 60 * 60 * 24 * 40,
    updatedAt: now - 1000 * 60 * 60 * 24 * 10,
    lastMessage: {
      id: 'msg_elena_old',
      conversationId: 'conv_archived_1',
      senderId: 'user_elena',
      timestamp: now - 1000 * 60 * 60 * 24 * 10,
      content: 'Keys exchanged and backed up safely.',
      type: 'text',
      status: 'read',
      reactions: [],
    }
  }
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  conv_sarah: [
    {
      id: 'msg_sarah_1',
      conversationId: 'conv_sarah',
      senderId: 'user_sarah',
      timestamp: now - 1000 * 60 * 60 * 4,
      content: 'Hey Pratham! Are you working on the Signal Web client today?',
      type: 'text',
      status: 'read',
      reactions: [],
      isDisappearing: true,
      expireTimerSeconds: 86400,
    },
    {
      id: 'msg_sarah_2',
      conversationId: 'conv_sarah',
      senderId: 'user_me',
      timestamp: now - 1000 * 60 * 60 * 3,
      content: 'Yes! Building the exact UI/UX from the desktop app in Next.js + Tailwind, fully decoupled for seamless backend integration.',
      type: 'text',
      status: 'read',
      reactions: [{ emoji: '🎉', count: 1, userIds: ['user_sarah'] }],
      isDisappearing: true,
      expireTimerSeconds: 86400,
    },
    {
      id: 'msg_sarah_3',
      conversationId: 'conv_sarah',
      senderId: 'user_sarah',
      timestamp: now - 1000 * 60 * 15,
      content: 'Awesome! Did you configure the Safety Number verification and audio call previews?',
      type: 'text',
      status: 'read',
      reactions: [],
      isDisappearing: true,
      expireTimerSeconds: 86400,
    },
    {
      id: 'msg_sarah_4',
      conversationId: 'conv_sarah',
      senderId: 'user_sarah',
      timestamp: now - 1000 * 60 * 2,
      content: 'Just deployed the new E2E verification test. Can you check on your side?',
      type: 'text',
      status: 'delivered',
      reactions: [{ emoji: '👍', count: 1, userIds: ['user_me'] }],
      replyTo: {
        id: 'msg_sarah_3',
        senderId: 'user_sarah',
        senderName: 'Sarah Connor',
        content: 'Awesome! Did you configure the Safety Number verification and audio call previews?',
      },
      isDisappearing: true,
      expireTimerSeconds: 86400,
      expiresAt: now + 86400 * 1000,
    }
  ],
  conv_alex: [
    {
      id: 'msg_alex_1',
      conversationId: 'conv_alex',
      senderId: 'user_alex',
      timestamp: now - 1000 * 60 * 60 * 2,
      content: 'Could you share the audio specs for the voice note recorder?',
      type: 'text',
      status: 'read',
      reactions: [],
    },
    {
      id: 'msg_alex_2',
      conversationId: 'conv_alex',
      senderId: 'user_me',
      timestamp: now - 1000 * 60 * 45,
      content: 'Here is the voice memo detailing the architecture:',
      type: 'audio',
      status: 'read',
      reactions: [{ emoji: '❤️', count: 1, userIds: ['user_alex'] }],
      attachments: [{
        id: 'att_voice_1',
        url: '/sounds/notification.ogg',
        fileName: 'Voice message.ogg',
        fileSize: 32667,
        mimeType: 'audio/ogg',
        duration: 14,
        waveform: [0.2, 0.4, 0.8, 0.6, 0.9, 0.3, 0.5, 0.7, 1.0, 0.4, 0.2, 0.6, 0.8, 0.5, 0.3, 0.7, 0.9, 0.4, 0.2],
      }],
    }
  ],
  conv_note_to_self: [
    {
      id: 'msg_nts_1',
      conversationId: 'conv_note_to_self',
      senderId: 'user_me',
      timestamp: now - 1000 * 60 * 12,
      content: 'Remember to verify the Safety Number before transmitting keys 🔑',
      type: 'text',
      status: 'read',
      reactions: [{ emoji: '📌', count: 1, userIds: ['user_me'] }],
      isNoteToSelf: true,
    }
  ]
};

export const DEFAULT_PREFERENCES: UserPreferences = {
  theme: 'dark',
  readReceipts: true,
  typingIndicators: true,
  soundEnabled: true,
  compactMode: false,
  defaultDisappearingTimer: 0,
};
